basic.forever(function () {
    Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Forward, 100)
    Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Forward, 100)
    if (input.buttonIsPressed(Button.A)) {
        Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Forward, 0)
        Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Forward, 0)
        basic.pause(300)
        Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Reverse, 100)
        Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Reverse, 100)
        basic.pause(500)
        Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Forward, 0)
        Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Forward, 0)
        basic.pause(300)
        Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Forward, 100)
        Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Reverse, 100)
        basic.pause(400)
        Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Forward, 0)
        Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Forward, 0)
        basic.pause(300)
    } else {
        if (input.buttonIsPressed(Button.B)) {
            Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Forward, 0)
            Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Forward, 0)
            basic.pause(300)
            Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Reverse, 100)
            Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Reverse, 100)
            basic.pause(500)
            Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Forward, 0)
            Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Forward, 0)
            basic.pause(300)
            Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Reverse, 100)
            Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Forward, 100)
            basic.pause(400)
            Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor1, Kitronik_IFF.MotorDirection.Forward, 0)
            Kitronik_IFF.motorOn(Kitronik_IFF.Motors.Motor2, Kitronik_IFF.MotorDirection.Forward, 0)
            basic.pause(300)
        }
    }
})
